### PR TITLE
feat: Display "No Data found" message when no data available

### LINKED ISSUE #7: Display a "No Data Found" message or image when data is unavailable.

### PR DESCRIPTION
**Pull request by bhav380-2**
Setted the default error parameter in the Error component to "No Data found" to ensure this message displays when data is unavailable. closes #7

### CODE REVIEW

**Comment by bhardwajdisha** [comment]
Can you attach a screenshot of your work?

**Comment by bhav380-2** [comment]
Yes mam. 
I have given my laptop for repair, I will receive it today by evening.
As soon as I get my system I will post the screenshot

**Comment by bhav380-2** [comment]
No data found message when data not available

Screenshot from 2024-09-26 20-21-39

**Review by bhardwajdisha — APPROVED** [review]

**Comment by bhardwajdisha** [comment]
Great Work @bhav380-2

**Pull request closed without merging**
