### PR TITLE
Login page enhancement

### LINKED ISSUE #6: Improve login page UI

### PR DESCRIPTION
**Pull request by bhav380-2**
Enhanced the layout and styling of the login page. 
closes #6

### CODE REVIEW

**Comment by bhardwajdisha** [comment]
Please add a screenshot of your work

**Comment by bhav380-2** [comment]
This is new login page.
loginPage

**Comment by bhardwajdisha** [comment]
Great work @bhav380-2

**Review by bhardwajdisha — APPROVED** [review]

**Comment by bhav380-2** [comment]
Thanks @bhardwajdisha

**Pull request merged**
